"""Duplicate-execution fencing for RC005 Wave 2 (C2)."""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from typing import Any

TERMINAL_STATUSES = frozenset({"completed", "failed", "cancelled", "blocked", "timed_out"})
ACKNOWLEDGED_STATES = frozenset({"ACKNOWLEDGED", "DISPATCH_UNKNOWN"})


def normalized_brief(brief: str | None) -> str:
    return " ".join(str(brief or "").split())


def brief_hash(brief: str | None) -> str:
    return hashlib.sha256(normalized_brief(brief).encode("utf-8")).hexdigest()


def fencing_key(*, goal: str | None, package_id: str, task_family: str | None,
                session_key: str | None, brief_digest: str) -> str:
    value = [goal or "", package_id, task_family or "", session_key or "", brief_digest]
    return hashlib.sha256(json.dumps(value, separators=(",", ":")).encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class FenceDecision:
    allowed: bool
    reason: str
    key: str


def check_dispatch_fence(
    *, record: dict[str, Any] | None, goal: str | None, package_id: str,
    task_family: str | None, session_key: str | None, brief_digest: str,
    reconciliation: dict[str, Any] | None = None,
) -> FenceDecision:
    key = fencing_key(goal=goal, package_id=package_id, task_family=task_family,
                      session_key=session_key, brief_digest=brief_digest)
    if not record:
        return FenceDecision(True, "no_prior_execution", key)
    status = str(record.get("status") or "not_started").lower()
    same_brief = record.get("brief_hash") == brief_digest
    same_family = (record.get("task_family") or "") == (task_family or "")
    same_session = bool(session_key and record.get("session_key") == session_key)
    acknowledged = str(record.get("dispatch_state") or "") in ACKNOWLEDGED_STATES
    recon = reconciliation or {}
    evidence = recon.get("evidence") or {}
    # A reconciliation decision is single-use: a CONSUMED decision must
    # never re-authorize dispatch through the fence (RC006 HIGH-3 fix:
    # racing process B must not reuse process A's consumed RETRY once the
    # package status has left EXECUTION_UNKNOWN).
    if recon.get("consumed") is True:
        return FenceDecision(False, "duplicate_nonterminal_dispatch", key) \
            if (status not in TERMINAL_STATUSES and acknowledged
                and same_brief and same_family) \
            else FenceDecision(True, "reconciliation_or_fresh_dispatch", key)
    # RETRY authorizes re-dispatch ONLY with authoritative proof the prior
    # execution is no longer live (RC006 HIGH-2 hardening: never treat a
    # bare RETRY record as authorization to replay an UNKNOWN).
    retry_authorized = (
        recon.get("decision") == "RETRY"
        and bool(evidence)
        and evidence.get("verified_dead") is True
        and evidence.get("death_evidence_authoritative") is True
    )
    resume_authorized = (
        recon.get("decision") == "RESUME" and bool(evidence)
    )
    if status not in TERMINAL_STATUSES and acknowledged and same_brief and same_family:
        # A non-terminal ACKNOWLEDGED package is already owned by a live
        # dispatch. Re-dispatching it under ANY session identity (same,
        # different, or absent) is a duplicate unless reconciliation
        # authorizes continuation of that exact ownership.
        if retry_authorized:
            # Retry REQUIRES a fresh session: the same session is the
            # old owner (denied); a different session is the fresh retry
            # session generated by the dispatcher (allowed). Concurrency
            # is protected by single-use consumption of the RETRY decision.
            if same_session:
                return FenceDecision(False, "retry_must_use_fresh_session", key)
            return FenceDecision(True, "reconciliation_or_fresh_dispatch", key)
        if resume_authorized:
            # RESUME authorizes the ORIGINAL session to continue; a
            # different or absent prospective session is not the owner.
            if same_session:
                return FenceDecision(True, "reconciliation_or_fresh_dispatch", key)
            return FenceDecision(False, "resume_requires_same_session", key)
        return FenceDecision(False, "duplicate_nonterminal_dispatch", key)
    return FenceDecision(True, "reconciliation_or_fresh_dispatch", key)
